name: Manual Publish

on:
  workflow_dispatch:

jobs:
  manual-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PAD }}" | docker login ghcr.io -u max-rohrhirsch --password-stdin
          
          docker buildx create --use
          docker buildx build \
            --platform linux/arm64 \
            -t ghcr.io/max-rohrhirsch/umoc-backend:latest . \
            --push
